spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  application:
    name: xg

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr([%X{requestId}]){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{requestId}] --- [%15.15t] %-40.40logger{39} : %m%n"

static:
  template: template
  tmp: tmp

u8:
  #url: http://127.0.0.1:3001/U8_API/
  url: http://119.29.241.24:8052/U8_API/