spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  application:
    name: xg

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: false

static:
  template: template
  tmp: tmp

u8:
  url: http://127.0.0.1:3001/U8_API/